CREATE TYPE claim_status as ENUM ('submitted', 'in progress', 'approved', 'denied');

CREATE TABLE claimants(
 customerIdNumber VARCHAR (20) PRIMARY KEY,
 claimantName VARCHAR (100) NOT NULL,
 claimantAddress VARCHAR (255) NOT NULL,
 claimantEmail VARCHAR (50),
 claimantPhone VARCHAR(15) NOT NULL,
 claimantNextOfKin VARCHAR (255) NOT NULL,
 claimantPolicyNumber INTEGER NOT NULL CHECK (claimantPolicyNumber > 9999999 AND  claimantPolicyNumber < 100000000),
 preExistingMedicalConditions VARCHAR (255),
 bankAccountNumber VARCHAR (50) NOT NULL
);

CREATE TABLE claims(
  claimId bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY(INCREMENT 1 MINVALUE 1000000000 MAXVALUE 9999999999),
  policyNumber INTEGER NOT NULL CHECK (policyNumber > 9999999 AND  policyNumber < 100000000),
  customerIdNumber VARCHAR(20) CONSTRAINT check_customerIdNumber CHECK ( customerIdNumber ~* '^[A-Z0-9 -]+$') NOT NULL,
  condition VARCHAR(255) NOT NULL,
  firstSymptoms DATE NOT NULL,
  symptomDetails VARCHAR(255) NOT NULL,
  serviceType VARCHAR (50) NOT NULL,
  providerFacility VARCHAR (50) NOT NULL,
  alternativeHealthInsurance BOOLEAN NOT NULL,
  consentStatement BOOLEAN NOT NULL,
  claimStatus claim_status DEFAULT 'submitted' NOT NULL, 
  CONSTRAINT fk_claimant
  	FOREIGN KEY(customerIdNumber)
  		REFERENCES claimants(customerIdNumber)
 );
 

